spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
server.port=8081

# MongoDB Connection
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=Engineering_Digest
#spring.data.mongodb.auto-index-creation=true

#Mongodb atlas
spring.data.mongodb.uri=mongodb+srv://mongo_db_atlas:atharva11@spring-security.8xapcw3.mongodb.net/?appName=spring-security
spring.data.mongodb.database=Engineering_Digest
spring.data.mongodb.auto-index-creation=true