spring.application.name=productSite
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url={your database urls}
spring.datasource.username={username}
spring.datasource.password = {password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
spring.jackson.deserialization.fail-on-null-for-primitives=false
spring.servlet.multipart.enabled=true

#for chat client
spring.ai.google.genai.api-key={api key}

#for image generation
spring.ai.stabilityai.api-key={stabillity api key}
spring.ai.stabilityai.image.options.model="model id or name"

#vector database quadrant
spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=port no

spring.ai.google.genai.project-id="project id"
spring.ai.google.genai.embedding.location=us-central1
spring.ai.google.genai.location=us-central1
spring.ai.google.genai.model-id="model id"
spring.ai.google.genai.embedding.text.options.model="embedding model"
spring.ai.google.genai.embedding.project-id="project id"
