spring.application.name=productSite
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
spring.datasource.username=root
spring.datasource.password = atharva11
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
spring.jackson.deserialization.fail-on-null-for-primitives=false
spring.servlet.multipart.enabled=true

#for chat client
spring.ai.google.genai.api-key=AIzaSyB1-XuPXQHw75_WAkSP92AnpeHWRXDOjf0

#for image generation
spring.ai.stabilityai.api-key=sk-uB4qpDfqxWQTCL99ntxLW829AQQSxspkP6PWUl8yGVGnSxYv
spring.ai.stabilityai.image.options.model=stable-diffusion-xl-1024-v1-0

#vector database quadrant
spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334 

spring.ai.google.genai.project-id=embedding-484717
spring.ai.google.genai.embedding.location=us-central1
spring.ai.google.genai.location=us-central1
spring.ai.google.genai.model-id=gemini_3_pro_review
spring.ai.google.genai.embedding.text.options.model=text-embedding-004
spring.ai.google.genai.embedding.project-id=embedding-484717